### ISSUE TITLE
Docker Image not Publicly Visible

### ISSUE THREAD

**Issue by ytausch** [Quansight-Labs/conda-metadata-app#16]
@jaimergp, I don't see the Docker Image pushed to GHCR here: https://github.com/orgs/Quansight-Labs/packages?repo_name=conda-metadata-app

Is this a permission issue? Would appreciate a fix! :)

**Comment by jaimergp** [comment]
Let me look into this, it's disabled org-wide.

**Comment by jaimergp** [comment]
Can you give it a try @ytausch? Thanks.

**Comment by ytausch** [comment]
Look good! Thank you!
