### ISSUE TITLE
Issues with package updates

### ISSUE THREAD

**Issue by h-vetinari** [Quansight-Labs/conda-metadata-app#2]
Currently, the app will (correctly IMO!) try to show the latest version and latest build. However, there's some mismatch between what the UI sees as the newest available version, and what's actually available in terms of artefact metadata. This often manifests in the following kind of errors (example is from just entering `boost-cpp`):
![image](https://github.com/Quansight-Labs/conda-metadata-app/assets/33685575/ccb5299c-b327-4f52-a625-be385409e133)

Using the dropdown to navigate to an older build usually works, but it's not a great user experience (especially for those who don't know this quirk and wrongly conclude that app is broken). So I think we should probably catch that error and fall back to the last version for which we have metadata.

The second issue is that there seems to be some source of substantial delay with adding _entirely new_ packages to the UI dropdown. For example, we added `libboost` builds 4 days ago, and they're still not visible in the UI. In many ways, this is the opposite extreme of the above problem. It would be good to understand (for me at least) where this delay comes from, and if we can somehow get it down to under one day.

**Comment by h-vetinari** [comment]
> We can probably use `conda-package-streaming` to fetch from Anaconda.org as a fallback, though, as long as the artifact is `.conda`.

All new builds should be `.conda`, so that sounds excellent!

**Comment by jaimergp** [comment]
Opened https://github.com/regro/conda-forge-metadata/pull/18 to add the fallback. Once merged we can redeploy here.

**Comment by jaimergp** [comment]
Closed by [c347819](https://github.com/Quansight-Labs/conda-metadata-app/commit/c3478191242c080fdbce24bbc74c1a107e9160e8)
