### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [Quansight-Labs/conda-metadata-app#8]
Hey there :wave: Just wanted to let you know that the app seems to be unavailable to due it using all available resources:
![Screenshot 2024-09-03 at 7 24 01 PM](https://github.com/user-attachments/assets/7cf8bc99-909e-4ac8-8626-3eb404e48436)

**Comment by jaimergp** [comment]
Thanks. Seems to be working again now, but I'll leave this open in case it happens again. Please do ping me so I can see the notification a bit earlier 😬

**Comment by jaimergp** [comment]
Just writing down that the app went down again with a 255 exit code, probably due to resource exhaustion. Pushed a commit with smaller cache sizes. Hopefully that makes it more stable at the cost of runtime performance. Fingers crossed 🤞

**Comment by jaimergp** [comment]
I'm noticing these more often again, possibly following the merge of #10 and follow-ups? @ytausch, would you mind taking a look at the code and see if there any leaks? In the past I had to reduce the amount of cache entries or their maximum lifetime. I recall you changed some bits there 😬  Thanks! 🙏

**Comment by jaimergp** [comment]
Yep, I've seen that. Before I did that I was experimenting with smaller caches because that's one of their requirements (tune your app), and got it to a point where it didn't OOM for a few weeks. Now the OOMs are back so I'd like to get it working again, because the app itself didn't change much, it was just a refactor.

**Comment by jaimergp** [comment]
We have obtained a resource increase. We have 8GB now, hopefully should be ok. And it's also good to know _how much_ we have because we didn't know before 😂

**Comment by JeanChristopheMorinPerso** [comment]
Great news!
